volumes:
  db:

services:

  db-postgres:
    container_name: weather-postgres
    image: postgres
    environment:
      POSTGRES_DB:        weather
      POSTGRES_USER:      root
      POSTGRES_PASSWORD:  root
    volumes:
      - db:/var/lib/postgresql/
    ports:
      - 5432:5432
  weatherapp:
    container_name: weather-api
    build: .
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_URL: jdbc:postgresql://db-postgres:5432/weather
      #every 1 minute, uses cron format
      SHCEDULED_UPDATE_WEATHER_INTERVAL: "0 */1 * * * *"